name: PR Tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: v20.13.1
      - name: Install dependencies
        run: |
          npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical
  npmtest:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm install semantic-release @semantic-release/exec pkg --save-dev
          npm install
      - name: Test
        run: npm test
